### ISSUE TITLE
Non-deductible?

### ISSUE THREAD

**Issue by loneprairie** [twomice/com.joineryhq.percentagepricesetfield#20]
Is it possible to set the percentage price field to be non-deductible?

Thanks!

**Comment by twomice** [comment]
It's not possible with the current features. It's not impossible to add that feature, though, but I think it's a little tricky, since "non-deductible amount" is a fixed amount and this field is a variable percentage.

**Comment by twomice** [comment]
Having not heard more demand for this feature, closing as "won't fix".  Willing to reconsider if the demand is significant, but noting that this may be difficult enough to warrant the need for paid sponsorship on this improvement.
