### ISSUE TITLE
"Disable for payment methods" setting ignored on Additional Participants forms?

### ISSUE THREAD

**Issue by catconner** [twomice/com.joineryhq.percentagepricesetfield#21]
Hi I really love this extension, but I've come across one problem -- Is there a way for the payment method choice made on the first form to persist to the additional participant registration forms?  

Here's how to reproduce my problem:
-- Create an event where one person can register multiple participants at once
-- Configure a percentage price field in a price set to add 3.5%, "Hide checkbox and force to "yes" is checked (to suppress the optional checkbox), and "Disable for payment methods" is selected for "Pay Later".
-- Go to the event registration page and say you are registering 2 people.
-- the first registration page works fine; the user is given a payment option choice, and the percentage is added only if they choose a payment processor, not for Pay Later
-- Click continue to load the additional participant form.  The total always adds 3.5 percent regardless of the choice made on the first form.

I realize that there is no "select payment method" section on Additional Participants forms, so I'm not sure how to make this work....

**Comment by twomice** [comment]
Thanks for suggesting this improvement. Yes, it would be good to make this happen. I'll need to look closer at how CiviCRM handles price set selections on multi-contact event registrations.

At present my volunteer hours for CiviCRM projects are full with other tasks. If this is urgent and you'd like to discuss paid support, please message me via joineryhq.com. Otherwise, I will try to work this in among other volunteer projects as time allows.

**Comment by catconner** [comment]
Thanks so much for the response!  For now I've been able to use your extension in its current form, so thank you so much for developing it.  If you are able to add in this feature, I think it would be a great addition. But my need for it isn't urgent.

**Comment by twomice** [comment]
Okay, we'll keep it in the queue for the next (heretofore unscheduled) round of improvements. Thanks!

**Comment by twomice** [comment]
Hi @catconner. I've implemented a fix in v1.2-beta6, which should be available in the next 24 hours or so for in-app upgrade on CiviCRM's _Extensions_ page.  Please try it and post your results here. Thanks!

**Comment by twomice** [comment]
Closing, assuming the fix is good, having not heard back from OP. @catconner if you find this issue persist please comment and re-open this issue.
