### ISSUE TITLE
Confirming that this extension is still updated?

### ISSUE THREAD

**Issue by jdkoelsch** [twomice/com.joineryhq.percentagepricesetfield#24]
HI, I see that there are a few long-standing open issues, and that the codebase hasn't been updated in awhile. Can you confirm that the extension is still being supported? Just want to verify before proceeding with an installation. Thanks!

**Comment by twomice** [comment]
Hi @jdkoelsch Yes, this extension is still supported. Thanks to your nudge, I've just now cleaned up some tickets that needed closing; there are now 2 issues marked as bugs, both of which seem related to the use of commas as decimal separators (as is common in Europe). I've not been able to prioritize those but could do so if I get more reports that it's affecting more people.

I know of several sites using this in CiviCRM 5.8.x and expect it should work fine in later versions as well. If you have any issues in the latest version (currently 5.15.1), please report them in this issue tracker.

**Comment by jdkoelsch** [comment]
Thanks so much for the fast response! I appreciate it, and the info regarding compatibility. Thanks for the contribution, too! Seems like it will be really helpful

**Comment by twomice** [comment]
@jdkoelsch Just checking in to see whether the install went well -- any issues worth reporting? (Also curious what version of CiviCRM you're using this on.)

Thanks!
