### ISSUE TITLE
Extra "0.00" appearing in Total

### ISSUE THREAD

**Issue by philmb** [twomice/com.joineryhq.percentagepricesetfield#44]
This has been the case for a while on our installation, and I've looked at the code a bit but couldn't determine where its happening. I'm guessing this is a conflict somewhere, because I'm sure it would have been fixed by now if it were a universal bug. Anyway, we have an extra "0.00" appearing in the total line, as per the images. If you could give me a general area of the code in which to look, I'd be glad to look into it more to see if I can sort it out.
![Screen Shot 2021-11-23 at 10 29 47 AM](https://user-images.githubusercontent.com/7117661/143065113-bdcaaaa6-e557-4d4c-9817-7943198219d7.png)
![Screen Shot 2021-11-23 at 10 30 13 AM](https://user-images.githubusercontent.com/7117661/143065287-0a597c34-4993-4ef1-b48a-efc3bb4cc901.png)

**Comment by twomice** [comment]
Yes, it could be something unique to your site. Thanks for looking into it yourself; this info may help:

Most of the on-page stuff is done in [public_price_set_form.js](https://github.com/twomice/com.joineryhq.percentagepricesetfield/blob/master/js/public_price_set_form.js). Actual display of the modified total is in [updateTotal()](https://github.com/twomice/com.joineryhq.percentagepricesetfield/blob/master/js/public_price_set_form.js#L71)

Please report any findings or further questions here.

**Comment by philmb** [comment]
Thanks. I've determined that CRM.percentagepricesetfield.monetarySymbol is evaluating to include a number (0) and not just the symbol. Changing line 77 of public_price_set_form.js to 
`cj('#percentagepricesetfield_pricevalue').html('$' + CRM.percentagepricesetfield.calculateTotal());`
is at least a temporary fix for me. Not helpful for the code to maintain a variety of symbols.

What would be helpful is to wrap the monetary symbol in a <span> or put it in a :before element so it can be accessed independently of the total. Then whenever someone encounters whatever quirk is bothering me, or just wanted to style the symbol differently, it could be dealt with through some simple css.

**Comment by philmb** [comment]
Just noticing that this is the same issue experienced in PR https://github.com/twomice/com.joineryhq.percentagepricesetfield/pull/33
I'm also using Joomla.

**Comment by twomice** [comment]
Thanks for closing @philmb .  Sorry I never got you a proper response, but if this is indeed the same as in #33 , then I expect it's also fixed by  d4ec43f .  I'm trying to clean out old tickets first, but plan to tag a new release this week.
