### ISSUE TITLE
$_GET causing problems on updated site

### ISSUE THREAD

**Issue by philmb** [twomice/com.joineryhq.percentagepricesetfield#50]
I am trying to update my site to Joomla 4 and php8. This extension is giving me the error: "Unknown named parameter $_GET"

1 | () | JROOT/media/civicrm/ext/com.joineryhq.percentagepricesetfield-1.5.1/percentagepricesetfield.php:213

This error breaks not just the extension, but all of civicrm.

**Comment by philmb** [comment]
That's it. Thank you!

**Comment by twomice** [comment]
Thanks @philmb and @MegaphoneJon !
