### ISSUE TITLE
Display issues on contribution page with the correct total amount preceeded by $0.00

### ISSUE THREAD

**Issue by yashodha** [twomice/com.joineryhq.percentagepricesetfield#53]
After upgrading CiviCRM to 5.46 and extension to 1.5.2

I can see display issues on contribution page/price set preview for the total display.

![pri](https://github.com/twomice/com.joineryhq.percentagepricesetfield/assets/3455173/79749d29-edbc-43b2-805c-2d608c9bd93c)

**Comment by yashodha** [comment]
I have submitted a PR https://github.com/twomice/com.joineryhq.percentagepricesetfield/pull/54
Can you please take a look?

**Comment by twomice** [comment]
@yashodha Per my comment in the PR, I think we can do a little better here, by taking steps to preserve the original configured currency format (spaces or not). I've put such a fix in branch 53_money_format (commit 68a91b9322424750c02f657836fd7e7c3b47f5e6). This removes the entire concept of `CRM.percentagepricesetfield.monetarySymbol` and just uses CiviCRM's native currency formatting.

 Could you try this branch https://github.com/twomice/com.joineryhq.percentagepricesetfield/tree/53_money_format and let me know your thoughts / findings?

**Comment by yashodha** [comment]
@twomice 
I have tested your patch and it works and retains the format for the amount as well. It can be merged. Thanks!
