### ISSUE TITLE
Always adding $1 and calculating based on that additional amount

### ISSUE THREAD

**Issue by skyjacobs** [twomice/com.joineryhq.percentagepricesetfield#57]
I have set up a Price Set that has only a set of amounts and no other config except adding the percentage field. The field is set to 2.5%, but it always calculates based on $1 more than the selected amount. When I remove the extension everything works as it should and there is no additional $1 listed. When enabled I chose a field, $1000 for example and get $1026.03 with 2.5% set on the extension field. If I then click on None (which should register $0), it gives me $1.03.

It's hard to imagine that there is something particular on my CiviCRM install that would cause this strange behavior. Initially I thought it was due to an open-ended price field I had added to the Price Set, which requires $1 as the base price on the back end, however I deleted that entire Price Set and created a new one without adding an open-ended field and the issue persists. 

See screenshots below.

![Screenshot 2024-04-30 at 10 51 19 AM](https://github.com/twomice/com.joineryhq.percentagepricesetfield/assets/43451421/457f2170-e6cd-4c90-9cf0-70661e69d2b1)
![Screenshot 2024-04-30 at 10 51 35 AM](https://github.com/twomice/com.joineryhq.percentagepricesetfield/assets/43451421/0b388c81-7414-406e-bdb0-7f91d81b629d)

**Comment by twomice** [comment]
I've reproduced this. Yes, very odd.

Tagging as bug.

**Comment by twomice** [comment]
A fix for this issue has been committed in 606aa53. If someonw wants to try the latest master, please report here whether that commit resolves the issue for you. Thanks for the report @skyjacobs !

**Comment by twomice** [comment]
I'll go ahead and close this, as I believe it's fixed in today's release of version 1.5.3. Please feel free to re-open if you believe it still needs attention under that version. Thanks!

**Comment by skyjacobs** [comment]
Seems perfect now. Appreciate the effort!
