### ISSUE TITLE
Use with Pay Balances

### ISSUE THREAD

**Issue by dinalondon** [twomice/com.joineryhq.percentagepricesetfield#8]
If user goes to their dashboard and chooses to "make a payment" on a balance via the "Pay Balances" feature, the convenience fee is not added to the transaction.

**Comment by twomice** [comment]
Note: this is specific to the OP's custom CiviCRM implementation and probably not of interest to other users.

**Comment by twomice** [comment]
Closing as "won't fix", as OP has communicated they'll not be needing this feature.
